use_frameworks!

platform :ios, '9.0'

target 'MSTestDemo1Project_Example' do
  pod 'MSTestDemo1Project', :path => '../'

  target 'MSTestDemo1Project_Tests' do
    inherit! :search_paths

    
  end
end
